Issue 2099 | Unified way of accessing security keywords
mozilla/bugbot pull request #2312
Opened 2023-12-27 07:09 UTC by shubham-s-del

## Checklist

- [ ] Type annotations added to new functions
- [ ] Docs added to functions touched in main classes
- [ ] Dry-run produced the expected results
- [ ] The [`to-be-announced`](https://github.com/mozilla/bugbot/labels/to-be-announced) tag added if this is worth announcing

2023-12-27 07:10 UTC, shubham-s-del commented
This is intended to fix this - https://github.com/mozilla/bugbot/issues/2099

2024-01-02 17:49 UTC, suhaibmujahid approved these changes
Thank you, @shubham-s-del!

Could you please link to the issue in the PR description?[^1]

[^1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

2024-01-10 19:01 UTC, shubham-s-del commented
> Thank you, @shubham-s-del!
> 
> Could you please link to the issue in the PR description?[1](#user-content-fn-1-03e4ca82a0fef397d784c8c1265a251f)
> 
> Did you do a dry-run test? Once you have done that, please check the "Dry-run produced the expected results" item in the description.
> 
> ## Footnotes
> 1. https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue [↩](#user-content-fnref-1-03e4ca82a0fef397d784c8c1265a251f)

Thanks for the review.
Sorry for the late reply.
added to the description.
Could you help me with steps to do the dry run test?

2024-01-10 20:41 UTC, suhaibmujahid requested changes
Thank you!

> Could you help me with steps to do the dry run test?

You can do a dry run by running `python -m bugbot.rules.RUE_NAME`, example:
```
python -m bugbot.rules.crash_small_volume
```

Before that you need to create a configuration file. See https://github.com/mozilla/bugbot#running-the-bot-rules

Just make sure to replace `bz_api_key` with your token from Bugzilla.

2024-01-10 20:41 UTC, suhaibmujahid commented on bugbot/rules/security_unhide_dups.py
> +                or any(keyword in SECURITY_KEYWORDS for keyword in bug["keywords"])
Why did you change `and` to `or` here?

2024-01-11 02:54 UTC, shubham-s-del commented on bugbot/rules/security_unhide_dups.py
> +                or any(keyword in SECURITY_KEYWORDS for keyword in bug["keywords"])
```suggestion
                and any(keyword in SECURITY_KEYWORDS for keyword in bug["keywords"])
```

2024-01-11 02:58 UTC, shubham-s-del commented on bugbot/rules/security_unhide_dups.py
> +                or any(keyword in SECURITY_KEYWORDS for keyword in bug["keywords"])
my mistake. corrected.

2024-01-11 03:00 UTC, shubham-s-del commented
> Thank you!
> 
> > Could you help me with steps to do the dry run test?
> 
> You can do a dry run by running `python -m bugbot.rules.RUE_NAME`, example:
> 
> ```
> python -m bugbot.rules.crash_small_volume
> ```
> 
> Before that you need to create a configuration file. See https://github.com/mozilla/bugbot#running-the-bot-rules
> 
> Just make sure to replace `bz_api_key` with your token from Bugzilla.


I see a 403 from crash-stats API.
```
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://crash-stats.mozilla.org/api/SuperSearch/?date=%3E%3D2024-01-04&date=%3C2024-01-11&signature=%5EEMPTY%3A+&signature=%5EOOM+&signature=%3DIPCError-browser+%7C+ShutDownKill&signature=%5Ejava.lang.OutOfMemoryError&_results_number=0&_facets_size=1000
```

Do I need LDAP or phabricator key for this too?

2024-01-11 03:27 UTC, suhaibmujahid commented
> I see a 403 from crash-stats API.
> ```
> requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://crash-stats.mozilla.org/api/SuperSearch/?date=%3E%3D2024-01-04&date=%3C2024-01-11&signature=%5EEMPTY%3A+&signature=%5EOOM+&signature=%3DIPCError-browser+%7C+ShutDownKill&signature=%5Ejava.lang.OutOfMemoryError&_results_number=0&_facets_size=1000
> ```

You need a key for crash-stats to run `crash_small_volume`: https://crash-stats.mozilla.org/api/tokens/.

> Do I need LDAP or phabricator key for this too?

No, you don't need them for `security_unhide_dups` or `crash_small_volume`.

2024-01-12 04:16 UTC, shubham-s-del commented
> > I see a 403 from crash-stats API.
> > ```
> > requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://crash-stats.mozilla.org/api/SuperSearch/?date=%3E%3D2024-01-04&date=%3C2024-01-11&signature=%5EEMPTY%3A+&signature=%5EOOM+&signature=%3DIPCError-browser+%7C+ShutDownKill&signature=%5Ejava.lang.OutOfMemoryError&_results_number=0&_facets_size=1000
> > ```
> 
> You need a key for crash-stats to run `crash_small_volume`: https://crash-stats.mozilla.org/api/tokens/.
> 
> > Do I need LDAP or phabricator key for this too?
> 
> No, you don't need them for `security_unhide_dups` or `crash_small_volume`.

Thanks

I did a dry-run, gist containing the result = https://gist.github.com/shubham-s-del/1530df5f287c621d863c79ab63c0c317

2024-01-12 05:09 UTC, suhaibmujahid approved these changes
Thank you, @shubham-s-del!

2024-01-12 05:10 UTC, merged