Make webcompat platform bugs without keyword use BQ data
mozilla/bugbot pull request #2480
Opened 2024-09-11 14:39 UTC by jgraham

This is considered the canonical source for the list of webcompat core bugs, so using it as the backend for the bug-bot rules avoids needing to duplicate the logic across multiple systems.

## Checklist

- [ ] Type annotations added to new functions
- [ ] Docs added to functions touched in main classes
- [x] Dry-run produced the expected results
- [ ] The [`to-be-announced`](https://github.com/mozilla/bugbot/labels/to-be-announced) tag added if this is worth announcing

2024-10-11 10:24 UTC, jgraham commented
@denschub can you review this from a webcompat point of view?

2024-10-11 12:01 UTC, denschub approved these changes
This makes sense, and allows us to ingest more bugs without having to change bugbot all the time, for example if we add more components to our pipeline.

2024-10-15 12:45 UTC, jgraham commented
@suhaibmujahid friendly ping for review :)

2024-10-15 13:46 UTC, suhaibmujahid reviewed
I tried testing it using BugBot's service account, bug I got the following error:

```
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/bigquery/v2/projects/moz-fx-dev-dschubert-wckb/jobs?prettyPrint=false: Access Denied: Project moz-fx-dev-dschubert-wckb: User does not have bigquery.jobs.create permission in project moz-fx-dev-dschubert-wckb.`
```

2024-10-18 09:54 UTC, jgraham commented
I've updated the permissions so the bugbot user can run jobs.

2024-10-18 15:09 UTC, suhaibmujahid approved these changes
LGTM! I retriggered the tests to make sure that everything is fine: https://community-tc.services.mozilla.com/tasks/LR46apbqTSKnjbQ-E_XSlg


Once we deploy the PR, the bugs in the dry-run will have the `webcompat:platform-bug` added.

## Dry-run

<p>
The following bugs are blocking web compatibility knowledge base entries, but don't have the webcompat:platform-bug keyword set:
</p>
<table style="border:1px solid black;border-collapse:collapse;" border="1">
<thead>
<tr>
<th>Bug</th>
<th>Summary</th>
</tr>
</thead>
<tbody>
<tr bgcolor="#E0E0E0">
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1869323">1869323</a>
</td>
<td>The login page does not fully load at account.wacom.com with ETP set to STRICT</td>
</tr>
<tr >
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1869311">1869311</a>
</td>
<td>Form not visible on hardwareluxx.de with Strict ETP</td>
</tr>
<tr bgcolor="#E0E0E0">
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1868964">1868964</a>
</td>
<td>Cookie banner is missing on accuweather.com with Strict ETP</td>
</tr>
<tr >
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1868953">1868953</a>
</td>
<td>Cookie banner is missing on weather.com with Strict ETP</td>
</tr>
<tr bgcolor="#E0E0E0">
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1868361">1868361</a>
</td>
<td>Slider for price/sugar content do not filter the product results on lcbo.com in Private mode</td>
</tr>
<tr >
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1868311">1868311</a>
</td>
<td>Missing &#34; Travel documents&#34; option from the &#34;About you&#34; section at alaskaair.com with ETP set to STRICT</td>
</tr>
<tr bgcolor="#E0E0E0">
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1866977">1866977</a>
</td>
<td>The login page does not open when clicking on the &#34;Log in&#34; button at help.ui.com with ETP set to STRICT</td>
</tr>
<tr >
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1866278">1866278</a>
</td>
<td>Bell button does not work on thedailystar.net in Private mode</td>
</tr>
<tr bgcolor="#E0E0E0">
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1866015">1866015</a>
</td>
<td>The page goes blank once the cookie policy is accepted katu.com with ETP set to STRICT</td>
</tr>
<tr >
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1865844">1865844</a>
</td>
<td>Page elements/text overlap with each other on atribuna.com.br with Strict ETP</td>
</tr>
<tr bgcolor="#E0E0E0">
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1865665">1865665</a>
</td>
<td>The page is blank at telltims.ca with ETP set to STRICT</td>
</tr>
<tr >
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1865330">1865330</a>
</td>
<td>The chatbot pop-up is not present on the &#34;Get in touch&#34; page at cloudflare.com with ETP set to STRICT</td>
</tr>
<tr bgcolor="#E0E0E0">
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1865118">1865118</a>
</td>
<td>The video does not play at crave.ca with ETP set to STRICT</td>
</tr>
<tr >
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1864438">1864438</a>
</td>
<td>The gallery is not shown due to an error message at redditp.com with ETP set to STRICT</td>
</tr>
<tr bgcolor="#E0E0E0">
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1864394">1864394</a>
</td>
<td>www.kaufland.ro - The page does not fully load in Private Browsing mode</td>
</tr>
<tr >
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1864169">1864169</a>
</td>
<td>The &#34;Start a chat&#34; option does not work when attempting to talk with an agent with ETP set to STRICT at hulu.com</td>
</tr>
<tr bgcolor="#E0E0E0">
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1863742">1863742</a>
</td>
<td>Captcha does not load when trying to register on ticketmaster.com with Strict ETP</td>
</tr>
<tr >
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1862935">1862935</a>
</td>
<td>Re-enable bogus MIME type tests in devtools/client/jsonview/test/browser_jsonview_content_type.js</td>
</tr>
<tr bgcolor="#E0E0E0">
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1861599">1861599</a>
</td>
<td>The CSS is broken at mapillary.com with ETP set to STRICT</td>
</tr>
<tr >
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1861597">1861597</a>
</td>
<td>The video is missing on n-tv.de with Strict ETP</td>
</tr>
<tr bgcolor="#E0E0E0">
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1860224">1860224</a>
</td>
<td>Categories/Images missing on puppis.com.ar with Strict ETP</td>
</tr>
<tr >
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1859713">1859713</a>
</td>
<td>Fails to upload attachment when contacting on investopedia.com with Strict ETP</td>
</tr>
<tr bgcolor="#E0E0E0">
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1859553">1859553</a>
</td>
<td>[meta] Breakages of blocking content trackers</td>
</tr>
<tr >
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1859490">1859490</a>
</td>
<td>&#34;TypeError: can&#39;t access property &#34;title&#34;, tab is undefined&#34; due to tabManager.getWrapper not finding a wrapper</td>
</tr>
<tr bgcolor="#E0E0E0">
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1859484">1859484</a>
</td>
<td>Chrome-compatible about:blank patch causes unwanted changed rectangles on browser/base/content/test/performance/browser_windowopen.js</td>
</tr>
<tr >
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1858624">1858624</a>
</td>
<td>The chat does not load on southwest.com with Strict ETP</td>
</tr>
<tr bgcolor="#E0E0E0">
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1857878">1857878</a>
</td>
<td>Product list is not fully loaded at ou.com.br with ETP set to STRICT</td>
</tr>
<tr >
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1857455">1857455</a>
</td>
<td>mUnderHiddenEmbedderElement propagation unreliable with iframe that remains at initial about:blank</td>
</tr>
<tr bgcolor="#E0E0E0">
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1856901">1856901</a>
</td>
<td>Logo image is missing on subscription.yahoo.net with Strict ETP</td>
</tr>
<tr >
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1856608">1856608</a>
</td>
<td>Page is blank after scrolling on 13wham.com with Strict ETP</td>
</tr>
<tr bgcolor="#E0E0E0">
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1856600">1856600</a>
</td>
<td>Unable to scroll on kfc.com with Strict ETP</td>
</tr>
<tr >
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1856576">1856576</a>
</td>
<td>The text is overlapped at prog.world with ETP set to STRICT</td>
</tr>
<tr bgcolor="#E0E0E0">
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1856330">1856330</a>
</td>
<td>With about:blank patch test_group_mouseevents.html turns from intermittent to perma orange</td>
</tr>
<tr >
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1856329">1856329</a>
</td>
<td>With about:blank patch test_ext_scripting_contentScripts.html runs scripts whose filter isn&#39;t supposed to match</td>
</tr>
<tr bgcolor="#E0E0E0">
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1855904">1855904</a>
</td>
<td>The page is blank on foxbaltimore.com after refresh with Strict ETP</td>
</tr>
<tr >
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1855472">1855472</a>
</td>
<td>The account picture does not load at bing.com/search with ETP set to STRICT</td>
</tr>
<tr bgcolor="#E0E0E0">
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1855113">1855113</a>
</td>
<td>Home Depot website&#39;s New Relic page-load-monitoring script slow leaks if using Content Blocking or other ad blocking</td>
</tr>
<tr >
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1854909">1854909</a>
</td>
<td>Certain games are not loading at now.gg with ETP set to STRICT</td>
</tr>
<tr bgcolor="#E0E0E0">
<td>
<a href="https://bugzilla.moz [...]

2024-10-18 15:11 UTC, suhaibmujahid requested changes

2024-10-18 15:11 UTC, suhaibmujahid commented on bugbot/rules/webcompat_platform_without_keyword.py
> +        SELECT core_bug
Error:
```
trim trailing whitespace.................................................Failed
```

Fix:

```suggestion
        SELECT core_bug
```

2024-10-21 15:07 UTC, suhaibmujahid approved these changes
LGTM! Thank you!

@jgraham if you are ok with the dry-run results in https://github.com/mozilla/bugbot/pull/2480#pullrequestreview-2378388883, I will merge and deploy the PR.

2024-10-21 16:38 UTC, jgraham commented
We noticed a problem with how this will interact with our ETL that's pulling things into Big Query. No changes are needed here, but please hold off merging this for now :)

2024-10-24 09:32 UTC, jgraham commented
@suhaibmujahid we've rolled out the ETL fixes; this should be good to merge now, thanks!

2024-10-24 13:30 UTC, merged